### ISSUE TITLE
config.toml only works in obs-studio folder

### ISSUE THREAD

**Issue by eristocrates** [aatikturk/obsws-python#23]
First off, I'm on windows 10, obs 29, and python 3.10, writing a python script. I wasn't getting the config.toml to provide connection details via a parameterless call to ReqClient(), so I stepped through with vscode via a launch.json set to attach to the obs process id and justmycode set to false. So, I load my script in obs with a breakpoint on _conn_from_toml and it turns out Path.cwd() in baseclient.py:40 is returning my obs path, not the script's path. Technically I can handle that by just putting the file in there, but this behavior is contrary to the readme so I thought I should reach out for documentation's sake.

**Comment by onyx-and-iris** [comment]
Hello.

Thanks for raising this issue. You are correct, the cwd may change depending on how your code is launched which as you say, may lead to a contradiction with the docs. We had the thought to extend the `_conn_from_toml` function to check a users home directory and modify the readme accordingly. Readmes for examples will need updating too.

This way any current users should not be affected but new users are advised to place `config.toml` in the home directory, otherwise, handle the details themselves and pass conn info in as parameters.
