### ISSUE TITLE
Proper way to disconnect from OBS

### ISSUE THREAD

**Issue by XcantloadX** [aatikturk/obsws-python#41]
There are no explicit "disconnect methods" in both ReqClient and EventClient. How can I safely close the connection?

**Comment by Randy-W** [comment]
`cl = obs.ReqClient(host=self.host, port=self.port, password=self.password, timeout=3)
**cl.base_client.ws.close()**`

**Comment by XcantloadX** [comment]
> `cl = obs.ReqClient(host=self.host, port=self.port, password=self.password, timeout=3)` **`cl.base_client.ws.close()`**

Yes but you have to dig into source code to figure that out.
And closing ws of a EventClient will cause a JSONDecodeError and then a WebSocketConnectionClosedException.

**Comment by onyx-and-iris** [comment]
Hi, thanks for raising the issue.

Yes that part is hidden in the ReqClient's `__exit__()` method which can be used with a context manager. The [scene_rotate example](https://github.com/aatikturk/obsws-python/blob/main/examples/scene_rotate/__main__.py) does demonstrate use of a context manager but it should probably be mentioned in the README. Further to that point we could add a specific disconnect() method too if that makes things clearer, if Adem agrees.

The event client is a different story, since recv() is blocking. So I can think of two approaches, making recv non-blocking but this means constantly catching WebSocketTimeoutException until we want to exit from the thread, I don't think we want to do that if possible.
Another option might be to use an event object, listen until its set, and set it on WebSocketConnectionClosedException. [Something like this](https://gist.onyxandiris.online/onyx_online/f043ba51058b4405b94c0ba497dccb91).

There may be other/better ways but I don't know them, so those would be my suggestions. If we do implement these changes it should be done carefully in case there is something I've overlooked.
