### ISSUE TITLE
Setting text and retrieving transform data for text results in stale transform data

### ISSUE THREAD

**Issue by nik312123** [aatikturk/obsws-python#44]
In Python, I am working on some code that changes text in OBS and then centers the text element.

Here is the relevant code:

```python
# OBS_REQUEST_CLIENT, TEXT_SOURCE_NAME, text_item_id, and text are all assigned before this point
OBS_REQUEST_CLIENT.set_input_settings(TEXT_SOURCE_NAME, {"text": text}, True)

text_item_transform = OBS_REQUEST_CLIENT.get_scene_item_transform("Scene", text_item_id).scene_item_transform

text_item_width = text_item_transform["sourceWidth"]
text_item_height = text_item_transform["sourceHeight"]

OBS_REQUEST_CLIENT.set_scene_item_transform(
    "Scene",
    text_item_id,
    {
        "scaleX": 1.0,
        "scaleY": 1.0,
        "positionX": (SCENE_WIDTH - text_item_width) / 2,
        "positionY": (SCENE_HEIGHT - text_item_height) / 2,
    }
)
```

However, having these two calls one after the other often results in stale data for the text item's width and height. I have to put a `sleep(0.1)` call after the call to `OBS_REQUEST_CLIENT.set_input_settings(...)` to prevent this. This does not seem like expected behavior unless I am mistaken.

**Comment by onyx-and-iris** [comment]
Hi, thanks for raising the issue.

It sounds like you're making calls that return responses after a period of time? Well the OBS websocket protocol does provide request/response ids for this purpose but it makes more sense to use in an async context. This interface has no async component. Maybe it's possible to have the baseclient req method check for a matching response id before returning a response but I'm not sure if we want to make that change.

@aatikturk any thoughts on this?

**Comment by nik312123** [comment]
Some other options that may also be useful to consider if you do not want this to be the default behavior (or if you do want this to be the default behavior but want the option to also be able to use the current behavior) is that you could add a parameter when initializing a client to specify this behavior or have a default parameter for methods that fall under returning responses after a period of time.

**Comment by aatikturk** [comment]
Hi,

We'll keep this default behavior for now. It seems more like an OBS or network issue to me. Because the first request in your code
`set_input_settings` simply sends the request and doesn't wait for a response and doesn't return anything. you can see it in the definition [here](https://github.com/aatikturk/obsws-python/blob/main/obsws_python/reqs.py#L772). 

As @onyx-and-iris mentioned there are options to implement this. when we add new methods introduced in latest obs websocket version, we'll consider our options. Thanks for raising this issue. 

Regards,
Adem
