### ISSUE TITLE
Create Record Chapter Request missing

### ISSUE THREAD

**Issue by G4PLS** [aatikturk/obsws-python#49]
Based on the specs there is CreateRecordChapter request
As far as I have seen this is not present in the request client.

I think this is quite new, 30.2.0, and were only in 30.2.2

![image](https://github.com/user-attachments/assets/dc2753d6-215c-49ef-ad52-01ff1aff4435)

**Comment by G4PLS** [comment]
Maybe im also just missing something?
When manually sending the CreateRecordChapter request I get a 501

Thats how I tried to send it: `self.request_client.send("CreateRecordChapter", {"chapterName": "TEST"})`

`Error while sending request CreateRecordChapter: Request CreateRecordChapter returned code 501.`

**Comment by aatikturk** [comment]
Hi G4PLS,

CreateRecordChapter method is introduced in obs websocket version 5.5 and currently this library supports methods up to version 5.0.  So this is not implemented yet.

For the error you got from your manual request, only thing I would suggest is to check your versions for both obs and websocket plugin.

I'll try myself and update you about my findings.

**Comment by G4PLS** [comment]
I have checked the WebSocket version again and im on Version 5.5.2
I have also checked the returned available_request list that gets send with `get_version()` and in there CreateRecordChapter is being found
`print(self.available_requests.__contains__(request_name))` prints True

The error remained the same: `Error while sending request CreateRecordChapter: Request CreateRecordChapter returned code 501.` 

This is the actual error that gets raised by obsws_python: `obsws_python.error.OBSSDKRequestError: Request CreateRecordChapter returned code 501.`

I tested the Request without recording or having the file format correctly for this but a 501 still seems not the correct response that should be returned.

**Comment by aatikturk** [comment]
Hi There, 
Sorry It took some time.  I've checked locally and here are my findings. 

Test env information
- I've used `self.request_client.send("CreateRecordChapter", {"chapterName": "TEST"})` this same request
- Obs and websocket version
![image](https://github.com/user-attachments/assets/f47bfb20-cc6d-4508-87bf-6f9fceea728c)


- when recording is not enabled   request throws `501 error`
- when recording is enabled, same request throws `702 error` which indicates wrong output video format for recordings.

![image](https://github.com/user-attachments/assets/cc7c4c9c-f03d-48c2-9593-5838fe0b70a3)

- after changing recording output format to Hybrid MP4  it worked. Below is the relevant settings page from obs.
![image](https://github.com/user-attachments/assets/6812c57a-aca5-42fa-bdac-31001b67cfd2)

In the [official document](https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md)it states that this method only supports Hybrid Mp4 format as of Obs version 30.2.0
![image](https://github.com/user-attachments/assets/34a79daf-8b3d-4de9-b286-94533752aa92)

for your last question, The error is not on the client side. Because client is actually making the request. When you're not recording this error occurs on the obs side and obs returns the error for your request. client simply outputs this error. so this is a normal behavior.
![image](https://github.com/user-attachments/assets/80233c66-8e47-4d92-813e-428fa6a948d6)

hope this helps.
Regards,
Adem
